/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Analisador_Semantico.model.SimboloSemantico;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruth
 */
public class IUTabelaSemantica extends javax.swing.JFrame {
    private static int linhaTabela = 0;
    /**
     * Creates new form IUTabelaSemantica
     */
    public IUTabelaSemantica() {
        initComponents();
        linhaTabela= 0;
        //jTableSimboloSemantico = new JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSimboloSemantico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableSimboloSemantico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lexema", "Categoria", "Tipo", "Valor Numérico", "Valor Booleano", "Escopo", "chave Símbolo", "utilizada?"
            }
        ));
        jScrollPane2.setViewportView(jTableSimboloSemantico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void addSimboloSemantico(SimboloSemantico s1){
        jTableSimboloSemantico.setValueAt(s1.getLexema(), IUTabelaSemantica.linhaTabela, 0);
        jTableSimboloSemantico.setValueAt(s1.getCategoria(), IUTabelaSemantica.linhaTabela, 1);
        jTableSimboloSemantico.setValueAt(s1.getTipo(), IUTabelaSemantica.linhaTabela, 2);
        jTableSimboloSemantico.setValueAt(s1.getValorNumerico(), IUTabelaSemantica.linhaTabela, 03);
        jTableSimboloSemantico.setValueAt(s1.isValorBoleano(), IUTabelaSemantica.linhaTabela, 4);
        jTableSimboloSemantico.setValueAt(s1.getEscopo(), IUTabelaSemantica.linhaTabela, 5);
        jTableSimboloSemantico.setValueAt(s1.getNomeSimbolo(), IUTabelaSemantica.linhaTabela, 6);
        jTableSimboloSemantico.setValueAt(s1.isUtilizado(), IUTabelaSemantica.linhaTabela, 7);
        DefaultTableModel modelo = (DefaultTableModel) jTableSimboloSemantico.getModel(); 
        modelo.addRow(new String[]{"", ""});
        IUTabelaSemantica.linhaTabela++;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUTabelaSemantica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUTabelaSemantica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUTabelaSemantica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUTabelaSemantica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUTabelaSemantica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSimboloSemantico;
    // End of variables declaration//GEN-END:variables
}
